version: '3.8'

services:
  web:
    build: ./notebook
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
     - ./notebook/:/usr/src/app
    ports:
     - 8000:8000
    env_file:
     - ./.env.dev
  db:
    image: postgres:14.2-alpine
    volumes:
     - postgres_volume:/var/lib/postgresql/data/
    environment:
     - POSTGRES_USER=django_user
     - POSTGRES_PASSWORD=django_password
     - POSTGRES_DB=django_db

volumes:
  postgres_volume:
